# Generated by Django 5.1.1 on 2024-09-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='settings',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='config',
            field=models.JSONField(default=dict),
        ),
    ]
