# Generated by Django 5.1.1 on 2024-10-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='resposne',
            new_name='response',
        ),
    ]
