# Generated by Django 5.1.1 on 2024-10-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_uploadedfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='ref_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
