# Generated by Django 5.1.1 on 2024-10-05 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_ref_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='ref_path',
        ),
        migrations.AddField(
            model_name='chat',
            name='attach',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.uploadedfile'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='vector_db_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
