# Generated by Django 5.1.1 on 2024-10-05 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_chat_ref_path_chat_attach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='attach',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.uploadedfile'),
        ),
    ]
