# Generated by Django 5.1.1 on 2024-10-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_customgpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgpt',
            name='long_description',
            field=models.TextField(default='Long'),
            preserve_default=False,
        ),
    ]
