# Generated by Django 5.1.1 on 2024-10-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_customgpt_long_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customgpt',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
